### ISSUE TITLE
Error on 'dotnet ef database update'

### ISSUE THREAD

**Issue by o4f6bgpac3** [jasonsturges/sqlite-dotnet-core#3]
Steps to reproduce:

Clone repository
Open Terminal (on Mac) and navigate to solution directory
Type 'dotnet build'
Type 'cd SqliteConsole.Infrastructure'
Type 'dotnet ef database update'
**Note error because using .Net Standard**
Change Infrastructure .csproj file to use netcoreapp2.1
Type 'dotnet build'
Type 'dotnet ef database update'
**Note error shown below**

> Unable to create an object of type 'SqliteConsoleContext'. Add an implementation of 'IDesignTimeDbContextFactory<SqliteConsoleContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.

**Comment by jasonsturges** [comment]
@o4f6bgpac3 Sorry, these projects were outside what I could maintain for a while.

This project is pretty dated - upgrade to .NET 7 is in progress.

Presume you've moved on by this point, but .NET Standard should be addressed in this coming update.

**Comment by jasonsturges** [comment]
@o4f6bgpac3 Went with .NET 7, as no new versions of .NET Standard will ever be released.
